### ISSUE TITLE
Naming Convention Check (snake_case, camelCase, etc.)

### ISSUE THREAD

**Issue by ricfio** [phparkitect/arkitect#180]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Implement `AllVariables` class in 'Rules' folder and `HaveNamingConvention` class in a the new 'ForVariables' folder to check that 'Variable Naming Convention' respects the desired naming convention such as 'snake_case', 'camelCase', 'lowercase', 'UPPERCASE', etc.

Variable Naming Convention are strings to use as constructor parameter of HaveNamingConvention class, its could be a PHP enum but it's better use constants to avoid to change PHP 7.1 as minimum PHP version requirement.

For the same reason, you could also add `AllConstants`, `AllMethods` or `AllFunctions` classes in 'Rules' so you could check the naming convention for various subset that usually have different naming conventions (for example constants are UPPERCASE).

Here a little configuration example about variables:

```
    $rule = Rule::allVariables()
        ->that(new ResideInOneOfTheseNamespaces('App\*'))
        ->should(new HaveNamingConvention('camelCase')) // or NamingConvention::camelCase
        ->because('we love camelCase naming convention');
```

**Comment by micheleorselli** [comment]
In regards to add an `AllVariables` or `AllConstants` rule I have to admit I am a bit torn adding this kind of checks for two main reasons:
- gathering information about all the variables could be expensive in term of time and memory since rule do not have direct access to parsed code: we create an intermediate representation (the `ClassDescription` objects) and we pass that to the rules. Adding all variable information in `ClassDescription` could be expensive to do
- enforcing CamelCase or snake_case is something a csfixer/sniffer should do just fine 

`AllMethods` and/or `AllFunctions` sound more interesting but again the main focus is to check for dependencies or class use like 

```
$rule = Rule::allMethods()
  ->that(new ResideInOneofThisNamespaces('App')
  ->should(new NotDependOnClass(DateTime::class)
  ->because('avoid DateTime, DateTimeImmutable is better')
```

What do you think?

**Comment by ricfio** [comment]
True, you have right, about CamelCase or snake_case you can still use tools such as PHP CS Fixer (for example), so it might be of little useful (with little added value) add this feature in PHPArkitect as well!
Additionally, phparkitect should be focused on the Arkitecture of your application and not on the code style.
I understand also that could be too expensive add this type of selectors such as `AllVariables` or `AllConstants`.
About `AllMethods` and `AllFunctions` coudl be useful but in this moment I have no idea when use it because we are talking about do not add the CamelCase or snake_case checks.

So, for me, you can close this issue but thinking about when could be useful add `AllMethods` and `AllFunctions`.
